name: Deploy Staging/Production

on:
  push:
    branches:
      - main

env:
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  DATADOG_SITE: datadoghq.eu
  DATADOG_API_HOST: app.datadoghq.eu

jobs:
  bump-version:
    name: Bump Version
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          default_bump: major
          create_annotated_tag: true
      
      - name: Bump verion output
        run: echo "::set-output new_tag=${{ steps.tag_version.outputs.new_tag }}"
    
    outputs:
      git_version: ${{ steps.tag_version.outputs.new_tag }}


  deploy-frontend-prod:
      runs-on: ubuntu-latest
      needs: bump-version
      
      steps:
        - run: echo ${{ needs.bump-version.outputs.git_version }}
      
